### ISSUE TITLE
Summary titles should reference what tool they are from (if any)

### ISSUE THREAD

**Issue by nahsra** [pixee/codemodder-java#295]
Right now, the summaries for codemods are inconsistent. If they are fed by an external scanner tool, we should reference them in the beginning, like this:

`(Acme) Improvement summary`

E.g., 

`(Sonar) Added missing @Override parameter`

**Comment by drdavella** [comment]
Is using parens the formatting that you want? Should we make this consistent in Python?

**Comment by drdavella** [comment]
I almost wonder whether CodeTF should have another (optional) field for this and maybe upstream tools should decide how to render it so that it's consistent?

**Comment by nahsra** [comment]
That seems way better. I mean, it's sort of guessable based on the codemod ID.

**Comment by drdavella** [comment]
Yeah true. I'll open a PR in https://github.com/pixee/codemodder-specs/pulls

**Comment by nahsra** [comment]
@drdavella this issue should be closed now, right? We should open another ticket to meet that spec.

**Comment by drdavella** [comment]
Yeah I think so unless you need this in the short term.
