### ISSUE TITLE
SQL parameterization codemod puts together weird strings

### ISSUE THREAD

**Issue by nahsra** [pixee/codemodder-java#300]
This codemod can makes a change to WebGoat that is difficult to read:

```diff
- "INSERT INTO access_log (time, action) VALUES ('" + time + "', '" + action "')";
+ INSERT INTO access_log (time, action) VALUES (?" + ", ?" + ")";
```

This change should be:

```bash
INSERT INTO access_log (time, action) VALUES (?, ?)
```

Current WebGoat `main` at time of writing has this issue. I think the change is functionally correct, but it’s so awkward to read that it was tripping a user up.

**Comment by nahsra** [comment]
This issue still occurs even after recent SQL parameterization improvements.

**Comment by andrecsilva** [comment]
> This issue still occurs even after recent SQL parameterization improvements.

Yes, I just laid the ground for fixing this in the previous PRs. Next PR will address this.
