### ISSUE TITLE
Fix Logger Name False Positive

### ISSUE THREAD

**Issue by gilday** [pixee/codemodder-java#306]
The fix logger name codemod erroneously changes `getLogger` calls that use the correct type albeit with a qualifying parent class.

For example, the codemod will change the following code in nested class `EnrollmentStrategy.Default`.
```java
private static final Logger logger = LoggerFactory.getLogger(EnrollmentStrategy.Default.class);
```
to
```java
private static final Logger logger = LoggerFactory.getLogger(Default.class);
```

The codemod is only supposed to correct loggers that use the wrong type. In this case, the type is correct, it just happens to be a nested type that includes the parent type.

![Screenshot 2024-03-13 at 2 01 55 PM](https://github.com/pixee/codemodder-java/assets/1431609/b9663ad9-2b16-4007-8eab-8ba8510fd6a6)

**Comment by nahsra** [comment]
Wrong repo. I'll re-make for you.
